name: Deploy BlockZ Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'package.json'
      - '.github/workflows/deploy-wiki-pages.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: VuePress Deploy
        uses: IT4Change/vuepress-build-and-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_SECRET }}
          TARGET_REPO: yitian77/yitian77.github.io
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: |
            npm install
            npm run build
          BUILD_DIR: docs/.vuepress/dist/
